# docker-compose.yml
#
# Author: Cristian Tala Sánchez
# License: MIT
# Website: https://cristiantala.cl
#
# Licencia MIT:
#
# Derechos de autor (c) 2023 Cristian Tala Sánchez
#
# Se concede permiso, sin cargo, a cualquier persona que obtenga una copia
# de este software y los archivos de documentación asociados (el "Software"), para
# usar el Software sin restricción, incluyendo sin limitación los derechos
# para usar, copiar, modificar, fusionar, publicar, distribuir, sublicenciar y / o vender
# copias del Software, y para permitir que las personas a quienes se les proporcione el Software lo hagan,
# sujeto a las siguientes condiciones:
#
# El aviso de derechos de autor anterior y este aviso de permiso se incluirán en
# todas las copias o partes sustanciales del Software.
#
# EL SOFTWARE SE PROPORCIONA "TAL CUAL", SIN GARANTÍA DE NINGÚN TIPO, EXPRESA O
# IMPLÍCITA, INCLUYENDO PERO NO LIMITADO A LAS GARANTÍAS DE COMERCIABILIDAD,
# APTITUD PARA UN PROPÓSITO PARTICULAR Y NO INFRACCIÓN. EN NINGÚN CASO
# LOS AUTORES O TITULARES DEL COPYRIGHT SERÁN RESPONSABLES DE NINGUNA RECLAMACIÓN, DAÑOS U OTRA
# RESPONSABILIDAD, YA SEA EN UNA ACCIÓN DE CONTRATO, AGRAVIO O CUALQUIER OTRO MOTIVO, QUE SURJA DE, FUERA DE O
# EN RELACIÓN CON EL SOFTWARE O EL USO U OTROS NEGOCIOS EN EL SOFTWARE.
#
#
# En este Gist se encuentra el docker-compose que permite el desarrollo sencillo de plugins para wordpress de manera local.
version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wp_plugin_dev_video_sitemap
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
    ports:
      - "81:80"
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:latest
    container_name: wp_db_video_sitemap
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: